node {

    checkout scm

    env.DOCKER_API_VERSION="1.23"
    
    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "eduassistweb"
    registryHost = "192.168.1.118:5000"
    imageName = "${registryHost}/${appName}:${tag}"
    
    env.BUILDIMG=imageName
    stage "Maven build"
        sh "mvn -f warzone-parent/pom.xml clean package"
       	sh "mv edu_assist-web/target/edu_assist-web.war warzone-parent"
    stage "Build"
        sh "docker build -t ${imageName} -f warzone-parent/Dockerfile warzone-parent"
    
    stage "Push"
        
        sh "docker push ${imageName}"

    stage "Deploy"

        sh "sed 's#192.168.1.118:5000/eduassistweb:latest#'$BUILDIMG'#' warzone-parent/deployment.yaml | kubectl apply -f -"
        sh "kubectl rollout status deployment/edu-assist-web"
}
